#!/bin/bash
set -e

timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
commit=$(git rev-parse --verify HEAD)

INPUT_AUTHOR_EMAIL=${INPUT_AUTHOR_EMAIL:-'github-actions[bot]@users.noreply.github.com'}
INPUT_AUTHOR_NAME=${INPUT_AUTHOR_NAME:-'github-actions[bot]'}
INPUT_COAUTHOR_EMAIL=${INPUT_COAUTHOR_EMAIL:-''}
INPUT_COAUTHOR_NAME=${INPUT_COAUTHOR_NAME:-''}
INPUT_MESSAGE=${INPUT_MESSAGE:-"CI ${timestamp} [${commit}]"}
INPUT_MESSAGE=${INPUT_MESSAGE//'${timestamp}'/$timestamp}
INPUT_MESSAGE=${INPUT_MESSAGE//'${commit}'/$commit}
INPUT_BRANCH=${INPUT_BRANCH:-master}
INPUT_DISTBRANCH=$INPUT_DISTBRANCH
INPUT_DISTFILES=$INPUT_DISTFILES
INPUT_FORCE=${INPUT_FORCE:-false}
INPUT_TAGS=${INPUT_TAGS:-false}
INPUT_EMPTY=${INPUT_EMPTY:-false}
INPUT_DIRECTORY=${INPUT_DIRECTORY:-'.'}
REPOSITORY=${INPUT_REPOSITORY:-$GITHUB_REPOSITORY}

echo 'Push to branch $INPUT_BRANCH of $REPOSITORY';
